CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    timezone VARCHAR(64) NOT NULL
);

CREATE TABLE calendars (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    CONSTRAINT fk_calendars_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE slots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calendar_id BIGINT NOT NULL,
    start_time TIMESTAMP WITH TIME ZONE NOT NULL,
    end_time TIMESTAMP WITH TIME ZONE NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'FREE',
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_slots_status CHECK (status IN ('FREE', 'BUSY')),
    CONSTRAINT ck_slots_time CHECK (end_time > start_time),
    CONSTRAINT fk_slots_calendar
        FOREIGN KEY (calendar_id) REFERENCES calendars (id)
);

CREATE TABLE meetings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slot_id BIGINT NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    organizer_id BIGINT NOT NULL,
    CONSTRAINT fk_meetings_slot
        FOREIGN KEY (slot_id) REFERENCES slots (id),
    CONSTRAINT fk_meetings_organizer
        FOREIGN KEY (organizer_id) REFERENCES users (id)
);

CREATE TABLE participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT uk_participants_meeting_user UNIQUE (meeting_id, user_id),
    CONSTRAINT fk_participants_meeting
        FOREIGN KEY (meeting_id) REFERENCES meetings (id),
    CONSTRAINT fk_participants_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_slots_calendar_start ON slots (calendar_id, start_time);
CREATE INDEX idx_slots_calendar_status_start ON slots (calendar_id, status, start_time);
CREATE INDEX idx_participants_user_id ON participants (user_id);
